"""Create Game Model

Revision ID: 4d9296668f75
Revises: faebd12f9523
Create Date: 2024-02-16 21:32:19.939940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import declarative_base



# revision identifiers, used by Alembic.
revision = '4d9296668f75'
down_revision = 'faebd12f9523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###